
name: Deploy multifib on EBS AWS

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Dockerfile
            context: client
            image: jegordev/lab2:fib-client
          - dockerfile: ./Dockerfile
            context: server
            image: jegordev/lab2:fib-server
          - dockerfile: ./Dockerfile
            context: worker
            image: jegordev/lab2:fib-worker
          - dockerfile: ./Dockerfile
            context: nginx
            image: jegordev/lab2:fib-router
    
    steps:

    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Buildx set-up
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: "{{defaultContext}}:${{ matrix.context }}"
        file: ${{ matrix.dockerfile }}
        push: true
        tags: ${{ matrix.image }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Auto Increment Semver Action
      uses: MCKanpolat/auto-semver-action@1.0.5
      id: versioning
      with:
        releaseType: minor
        incrementPerCommit: false
        github_token: ${{ secrets.ACCESS_GITHUB_TOKEN }}

    - name: Next Release Number
      run: echo ${{ steps.versioning.outputs.version }}

    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Generate deployment package
      run: zip deploy.zip ./docker-compose.yml

    - name: Deploy to EBS
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Zadandwa
        environment_name: Zadandwa-env
        version_label: 1.0.0
        region: us-east-1
        deployment_package: deploy.zip